apiVersion: v1
kind: Service
metadata:
  name: my-services
  labels: 
    app: manoj-app
spec:
  selector:
    app: manoj-app
  type: NodePort
  ports:
  - nodePort: 31000
    port: 80
    targetPort: 80      
